CREATE DATABASE GV_Agendamento;

USE GV_Agendamento;

CREATE Table Membros (
    ID_MENBRO INT PRIMARY KEY AUTO_INCREMENT,
    NOME_MEMBRO VARCHAR(50) NOT NULL,
    DATA_NASCIMENTO DATE,
    DATA_AGENDAMENTO DATE
);